---
# Implement it proberly for differing OSs https://kubernetes.io/docs/setup/cri/
- name: Containerd | Copy containerd binaries
  unarchive:
    src: "{{local_release_dir}}/containerd-linux-amd64-{{ containerd_version }}.tar.gz"
    dest: "{{ bin_dir}}"
    mode: 0755
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Containerd | Copy runc binary
  copy:
    src: "{{local_release_dir}}/runc-linux-amd64-{{ runc_version }}"
    dest: "{{ bin_dir}}/runc"
    mode: 0755
    remote_src: yes

- name: Copy crictl config file to the node
  template:
    src: ../templates/crictl.yaml.j2
    dest: "/etc/crictl.yaml"
    owner: root
    mode: 0644

- name: Containerd | Copy crictl binary
  unarchive:
    src: "{{local_release_dir}}/crictl-linux-amd64-{{ crictl_version }}.tar.gz"
    dest: "{{ bin_dir}}"
    mode: 0755
    remote_src: yes

- name: Containerd | Create directory for containerd hooks
  file:
    path: /etc/containerd
    state: directory
    owner: root
    mode: 0755

- name: Containerd | Install containerd config
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: Containerd | Install containerd systemd unit file
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service

- name: Containerd | Start containerd service
  service:
    name: containerd
    state: restarted
    enabled: yes

- name: Containerd | Stop and disable docker
  service:
    name: docker
    state: stopped
    enabled: false
  failed_when: false

- name: Containerd | Remove docker service file
  file:
    path: /run/systemd/system/docker.service
    state: absent
